# Generated by Django 2.2.4 on 2022-09-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220921_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='fav_devices',
        ),
        migrations.AddField(
            model_name='users',
            name='fav_devices',
            field=models.ManyToManyField(blank=True, to='account.Devices'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
