# Generated by Django 4.2.5 on 2023-11-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220922_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='friend_id',
            field=models.ManyToManyField(to='account.users'),
        ),
    ]
