# Generated by Django 5.0 on 2024-01-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_users_friend_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="friend_id",
        ),
        migrations.AddField(
            model_name="users",
            name="friends",
            field=models.ManyToManyField(blank=True, to="account.users"),
        ),
    ]
