# Generated by Django 2.2.4 on 2022-09-22 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='game_id',
            new_name='game_api_id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='game',
        ),
        migrations.AddField(
            model_name='games',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Reviews'),
        ),
    ]
