# Generated by Django 2.2.4 on 2022-09-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20220922_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='game_api_id',
            field=models.IntegerField(null=True),
        ),
    ]
