# Generated by Django 2.2.4 on 2022-09-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_reviews_game_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='fav_games',
            field=models.ManyToManyField(blank=True, related_name='favorite_games', to='account.Users'),
        ),
    ]
